version: "3.8"
services:
  database:
    image: mongo
    container_name: mongodb
    volumes:
      - my-mongo-data:/data/db
    restart: always
    networks:
      - lemoncode-challenge
  backend:
    depends_on:
      - database
    image: backend
    container_name: my-backend
    ports:
      - "5000:80"
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    networks:
      - lemoncode-challenge
  frontend:
    image: frontend
    container_name: my-frontend
    ports:
      - "3000:3000"
volumes:
  my-mongo-data:
networks:
  lemoncode-challenge:
