stages:
  - cloneProject

cloneProject:springapp:
  image:
    name: alpine/git:latest
    entrypoint: [""]
  stage: cloneProject
  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.local >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh git@gitlab.local
    - git clone git@gitlab.local:bootcamp/springapp.git
